apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtubr-api-ingress
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: "websecure"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
spec:
  ingressClassName: traefik
  rules:
    - host: dev-api.semperstream.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: youtubr-api-cpu-service
                port:
                  number: 3000
  tls:
    - hosts:
        - dev-api.semperstream.io
      secretName: dev-api-semperstream-tls
