apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtube-front-ingress
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"
spec:
  ingressClassName: traefik
  rules:
    - host: dev-app.semperstream.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: youtube-front-svc
                port:
                  number: 80
  tls:
    - hosts:
        - dev-app.semperstream.io
      secretName: youtube-ui-tls
