apiVersion: v1
kind: Service
metadata:
  name: youtube-stream-worker
  namespace: dev
  labels:
    app: youtube-stream-worker
spec:
  type: ClusterIP
  selector:
    app: youtube-stream-worker
    component: worker
  ports:
    - name: http
      port: 3001
      targetPort: 3001
